### ISSUE TITLE
New messages are not visible

### ISSUE THREAD

**Issue by amitavroy** [launcher-host/mercurius#1]
# New messages are not visible after hitting the enter button

## Description
After I logged inside the application and send a message to someone, I didn't see my own message. The scroll was somewhere showing old messages even when I have gone through all of them,

**Comment by akazorg** [comment]
Thanks for the report @amitavroy.

This was fixed with the latest release [0.0.6](https://github.com/launcher-host/mercurius/releases/tag/0.0.6).
