### ISSUE TITLE
Nothing is working , i get javascript dialog box error for everything 

### ISSUE THREAD

**Issue by sabina1997** [launcher-host/mercurius#30]
# Nothing is working , i get javascript dialog box error for everything

## Server environment
 - PHP:      v7.1.3
 - Laravel:  v5.7
 - Database: MySQL 10.1.34-MariaDB

## Description
I go to /messages and  and a popup shows with error message: An error was occurred while loading notifications. When i try to search users to start a conversation , another popup with same error for messages. In short, nothing is working , what i am missing?

**Comment by akazorg** [comment]
Hi @sabina1997, 

You are definitely missing the web console, copy the error log and share it with us.

Mercurius is currently in `alpha` version, which means bugs might occur and breaking changes will happen.

Fell free to open a new issue with a descriptive error log.
Thank you.
