### ISSUE TITLE
Typing indicator not working on 1.0.0-alpha.2

### ISSUE THREAD

**Issue by alextime** [launcher-host/mercurius#39]
Hi, I tried to install 1.0.0-alpha.2 version and typing indicator method @onInput() is never called (and that feature does not work, is it a normal behavior on 1.0.0-alpha.2?

**Comment by akazorg** [comment]
Hey @alextime, the typing indicator should be working, I've tested locally and the [demo online](http://mercurius-demo.herokuapp.com/login). 

Have you updated the assets? If not, run:
```
php artisan vendor:publish --tag="mercurius-public" --force
```
Thanks

**Comment by alextime** [comment]
Yes, I have installed a fresh Laravel 5.7 and launcher/mercurius:1.0.0-alpha.2 If I look into the compiled js library under public/vendor actually there is the onTyping method but it simply does not work. I also tried in another laravel 5.7 installation with the same problem, what do I miss? Wonderful package anyway!

**Comment by alextime** [comment]
I think I found the problem: even if I install the package using composer require launcher/mercurius:1.0.0-alpha.2 I am getting the commit 46364744a197fb5504c1eee645c5c393ebd7884c and not the latest d6d3905a17fece4aff2f806e702a48ad21842db4. I know it is not related to mercurius but I do you specify that specific commit when you require or update the package?

**Comment by alextime** [comment]
composer require launcher/mercurius:dev-master sorry for the silly question...but even if I am on the latest commit now (d6d3905) I cannot get the typing indicator working anyway :-(

**Comment by alextime** [comment]
I am checking pusher, realtime messages works fine anyway. Looking at vue dev tool I see that typing boolean data in Composer component never switch to true. Moving to slack right now. Thanks for your help

**Comment by alextime** [comment]
You were right, pusher debug console was the right place to look at. It is necessary to enable "Enable client events" on app setting of course, which is not enabled by default. I think could be a good idea to mention this aspect in the docs. Thanks again!
