### ISSUE TITLE
Callbacks on routes does not allow to cache routes

### ISSUE THREAD

**Issue by alextime** [launcher-host/mercurius#41]
Is it possibile to move form callbacks on route to controllers? Otherwise it is not possibile to cache routes file.

**Comment by akazorg** [comment]
great idea @alextime, can you submit a PR for that? Thanks

**Comment by alextime** [comment]
> great idea @alextime, can you submit a PR for that? Thanks

Ok, I've submitted a PR but keep in mind that this is my first PR...so...double check please...

**Comment by akazorg** [comment]
Merged with #42
